let rid = process.argv[2]                                                                                                                                                                                           
let server = process.argv[3]                                                                                                                                                                                        
let load = parseFloat(process.argv[4])                                                                                                                                                                              
                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                        
const BusinessNetworkConnection = require('composer-client').BusinessNetworkConnection;                                                                                                                             
var cardname = 'admin@641net';                                                                                                                                                                                      
                                                                                                                                                                                                                    
async function func() {                                                                                                                                                                                             
    let bizNetworkConnection = new BusinessNetworkConnection();                                                                                                                                                     
                                                                                                                                                                                                                    
    let businessNetworkDefinition = await bizNetworkConnection.connect(cardname);                                                                                                                                   
    let requestReg = await bizNetworkConnection.getAssetRegistry('org.example.osnet.Request');                                                                                                                      
    let factory = businessNetworkDefinition.getFactory();                                                                                                                                                           
    let request = await requestReg.get(rid);                                                                                                                                                                        
                                                                                                                                                                                                                    

    request.requestID=rid;                                                                                                                                                                                          
    request.servingInstance=server;                                                                                                                                                                                 
    request.serverLoad = load;                                                                                                                                                                                      
    await requestReg.update(request);                                                                                                                                                                               
                                                                                                                                                                                                                    
    process.stdout.write("true");                                                                                                                                                                                   
    process.exit();                                                                                                                                                                                                 
}                                                                                                                                                                                                                   
                                                                                                                                                                                                                    
func();           
